### ISSUE TITLE
getObserverLog

### ISSUE THREAD

**Issue by thomgb** [typemytype/loggerRoboFontExtension#1]
Time for 1.7? :) 

```
Traceback (most recent call last):
  File "extensionLogViewer.py", line 1, in <module>
ImportError: cannot import name getObserverLog
```

**Comment by typemytype** [comment]
oh thanks fixed in https://github.com/typemytype/loggerRoboFontExtension/commit/d4499128b18594aa1ac2643f6baaaddec43232ff

it is required to have the upcoming 1.7
